services:
  - type: web
    name: shorthand-reddit-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run reddit_dash.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6