services:
  - type: web
    name: shorthand-reddit-intelligence
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run reddit_dash.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18